AWSTemplateFormatVersion: '2010-09-09'

Description: Creates generic lambda layer.

Resources:
  LambdaOracleLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: !Ref S3BUCKET
        S3Key: !Ref ZipFileName
      Description: !Sub 'Lambda layer for ${LambdaLayerName}'
      LayerName: !Ref LambdaLayerName

Parameters:
    AppID:
        Type: String
    Role: 
        Type: String
    SecurityGroup:
        Type: CommaDelimitedList
    Subnet:
        Type: CommaDelimitedList
    UserID:
        Type: String
    StackName:
        Type: String
    KmsKeyArn:
        Type: String
    ENV:
        Type: String
    ZipFileName:
        Description: The Name of the ZipFile with Lambda Code
        Type: String
    S3BUCKET:
        Description: S3 bucket
        Type: String
    LambdaLayerName:
        Type: String

